# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: An Hour in The City
email: chrisinajar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  One hour. 30 Days. I hope this isn't boring.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anhourinthecity.com" # the base hostname & protocol for your site
twitter_username: kilbanks
github_username:  kilbanks

exclude: [vendor]

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true

prose:
  rooturl: 'hair/_posts'
  siteurl: 'http://anhourinthecity.com/'
  media: 'images/hair/'
  metadata:
    hair/_posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "text"
          value: "CURRENT_DATETIME"
          label: "Post date"
